-- Importación del inventario del estudio (enviado por Cristina).
-- Añade los artículos SIN borrar nada y SIN duplicar (dedup por nombre).
-- Ejecutar en Supabase -> SQL Editor -> Run. Se puede re-ejecutar sin problema.

insert into inventario (articulo, categoria, cantidad_total)
select v.articulo, v.categoria, v.cantidad
from (values
  ('Varias rosas y peonías', 'Flores y ramaje', null),
  ('Ramas artificiales', 'Flores y ramaje', null),
  ('Gladiolos rosas artificiales', 'Flores y ramaje', 34),
  ('Rosas rosas, verdes y blancas', 'Flores y ramaje', null),
  ('Guirnaldas de rosas fucsia', 'Flores y ramaje', null),
  ('Amapolas amarillas', 'Flores y ramaje', null),
  ('Liliums amarillos', 'Flores y ramaje', null),
  ('Plumas grandes', 'Flores y ramaje', 24),
  ('Paniculatas blancas', 'Flores y ramaje', null),
  ('Astromelias naranjas', 'Flores y ramaje', null),
  ('Cactus artificiales', 'Flores y ramaje', 2),
  ('Cajas con hiedras', 'Flores y ramaje', 2),
  ('Caja con pampas', 'Flores y ramaje', 1),
  ('Cajas con helechos', 'Flores y ramaje', 2),
  ('Girasoles', 'Flores y ramaje', null),
  ('Hortensias blancas', 'Flores y ramaje', null),
  ('Rosas blancas', 'Flores y ramaje', null),
  ('Varias flores tropicales', 'Flores y ramaje', null),
  ('Guirnaldas de helechos', 'Flores y ramaje', null),
  ('Cajas con flores preservadas', 'Flores y ramaje', 7),
  ('Caja con confeti biodegradable', 'Flores y ramaje', 1),
  ('Caja con musgo preservado', 'Flores y ramaje', 1),
  ('Hojas de palmera natural seca', 'Flores y ramaje', null),
  ('Faroles de madera burdeos', 'Decorativos / Mobiliario', 2),
  ('Faroles de mimbre', 'Decorativos / Mobiliario', 4),
  ('Faroles blancos', 'Decorativos / Mobiliario', 8),
  ('Faroles grandes blancos', 'Decorativos / Mobiliario', 2),
  ('Varios portavelas de distintas formas y tamaños', 'Decorativos / Mobiliario', null),
  ('Atriles', 'Decorativos / Mobiliario', 4),
  ('Diversas cajas de madera de distintos tamaños y formas', 'Decorativos / Mobiliario', null),
  ('Pedestales dorados para centros en altura', 'Decorativos / Mobiliario', 10),
  ('Rodajas/cortezas grandes de madera para centros de mesa', 'Decorativos / Mobiliario', 13),
  ('Rodajas ligeras de madera para centros de mesa', 'Decorativos / Mobiliario', 9),
  ('Rodajas grandes de madera', 'Decorativos / Mobiliario', 5),
  ('Bajoplatos de madera', 'Decorativos / Mobiliario', 13),
  ('Asientos turquesa para novios', 'Decorativos / Mobiliario', 2),
  ('Bandejas originales de madera', 'Decorativos / Mobiliario', 3),
  ('Pizarras', 'Decorativos / Mobiliario', 11),
  ('Peana azul para cartel flecha', 'Decorativos / Mobiliario', 1),
  ('Barricas de vino antiguas', 'Decorativos / Mobiliario', 3),
  ('Candelabros de madera', 'Decorativos / Mobiliario', 3),
  ('Soporte para rincón de limonada', 'Decorativos / Mobiliario', 1),
  ('Peana de madera para cartel', 'Decorativos / Mobiliario', 1),
  ('Candelabros de bronce antiguos', 'Decorativos / Mobiliario', 2),
  ('Cesto con telas de yute', 'Decorativos / Mobiliario', 1),
  ('Banquito de madera pequeño', 'Decorativos / Mobiliario', 1),
  ('Cajas de fruta antiguas', 'Decorativos / Mobiliario', 6),
  ('Cojines para columpio', 'Decorativos / Mobiliario', 2),
  ('Varios cojines vintage', 'Decorativos / Mobiliario', null),
  ('Tela de yute para arco', 'Decorativos / Mobiliario', null),
  ('Tela verde para arco', 'Decorativos / Mobiliario', null),
  ('Tela blanca para arco', 'Decorativos / Mobiliario', null),
  ('Tela de tul para arco', 'Decorativos / Mobiliario', null),
  ('Tela dorada para photocall', 'Decorativos / Mobiliario', null),
  ('Máquina de escribir antigua', 'Decorativos / Mobiliario', 1),
  ('Carro verde para portes', 'Decorativos / Mobiliario', 1),
  ('Carro negro para portes', 'Decorativos / Mobiliario', 1),
  ('Carro naranja para portes', 'Decorativos / Mobiliario', 1),
  ('Vasijas de barro', 'Decorativos / Mobiliario', 4),
  ('Macetero blanco', 'Decorativos / Mobiliario', 1),
  ('Pedestales de cerámica blancos', 'Decorativos / Mobiliario', 8),
  ('Maletas y baúles antiguos', 'Decorativos / Mobiliario', 13),
  ('Globo terráqueo', 'Decorativos / Mobiliario', 1),
  ('Lechera verde antigua', 'Decorativos / Mobiliario', 1),
  ('Gramola antigua', 'Decorativos / Mobiliario', 1),
  ('Ventana verde antigua', 'Decorativos / Mobiliario', 1),
  ('Silla tapizada en capitoné', 'Decorativos / Mobiliario', 1),
  ('Diván de terciopelo marfil', 'Decorativos / Mobiliario', 1),
  ('Tocador con espejo', 'Decorativos / Mobiliario', 1),
  ('Camarera (carrito para bebidas vintage)', 'Decorativos / Mobiliario', 1),
  ('Puerta antigua rústica con cristal', 'Decorativos / Mobiliario', 1),
  ('Consola gris desgastada de doble cajón', 'Decorativos / Mobiliario', 1),
  ('Ventana de cristal para seating plan', 'Decorativos / Mobiliario', 1),
  ('Columpio vintage', 'Decorativos / Mobiliario', 1),
  ('Escalera antigua con estantes', 'Decorativos / Mobiliario', 1),
  ('Biombo de forja', 'Decorativos / Mobiliario', 1),
  ('Estantes de cajas en altura para rincón de alpargatas', 'Decorativos / Mobiliario', 2),
  ('Banco para asiento de novios tapizado en capitoné', 'Decorativos / Mobiliario', 1),
  ('Consola retro de 3 cajones', 'Decorativos / Mobiliario', 1),
  ('Jaula de hierro grande', 'Decorativos / Mobiliario', 1),
  ('Mesas de apoyo art decó', 'Decorativos / Mobiliario', 2),
  ('Carrito antiguo pequeño', 'Decorativos / Mobiliario', 1),
  ('Carro rústico grande', 'Decorativos / Mobiliario', 1),
  ('Árbol preservado', 'Decorativos / Mobiliario', 1),
  ('Lámpara años 20', 'Decorativos / Mobiliario', 1),
  ('Consola rústica', 'Decorativos / Mobiliario', 1),
  ('Caja de mimbre', 'Decorativos / Mobiliario', 1),
  ('Escritorio antiguo', 'Decorativos / Mobiliario', 1),
  ('Sofá rosa', 'Decorativos / Mobiliario', 1),
  ('Estructura blanca para colocar fotos', 'Decorativos / Mobiliario', 1),
  ('Marco antiguo dorado', 'Decorativos / Mobiliario', 1),
  ('Mesa rústica para eventos', 'Decorativos / Mobiliario', 1),
  ('Arcos para ceremonia', 'Decorativos / Mobiliario', 2),
  ('Pedestales blancos (1 convertible en atril)', 'Decorativos / Mobiliario', 4),
  ('Peana de madera para colocar flecha/cartel', 'Decorativos / Mobiliario', 1),
  ('Candelabros altos de hierro', 'Decorativos / Mobiliario', 2),
  ('Puertas antiguas verdes', 'Decorativos / Mobiliario', 2),
  ('Trasera de madera', 'Decorativos / Mobiliario', 1),
  ('Marco grande para seating plan', 'Decorativos / Mobiliario', 1),
  ('Soportes de hierro altos para decorar', 'Decorativos / Mobiliario', 2),
  ('Consola retro de 5 cajones', 'Decorativos / Mobiliario', 1),
  ('Cornucopia antigua (espejo de marco antiguo)', 'Decorativos / Mobiliario', 1),
  ('Banco rústico con tapa con 2 cojines', 'Decorativos / Mobiliario', 1),
  ('Luna de forja desmontable actualmente decorada con preservado', 'Decorativos / Mobiliario', 1),
  ('Consola antigua con encimera de piedra con 2 faroles de madera', 'Decorativos / Mobiliario', 1),
  ('Neón de pared con el nombre de la marca', 'Decorativos / Mobiliario', 1),
  ('Bicicleta retro', 'Decorativos / Mobiliario', 1),
  ('Atril grande', 'Decorativos / Mobiliario', 1),
  ('Espejo para cartel de bienvenida', 'Decorativos / Mobiliario', 1),
  ('Diversos carteles y señalética realizados anteriormente', 'Decorativos / Mobiliario', null),
  ('Mueble alto con puertas de cristal (en baño)', 'Decorativos / Mobiliario', 1),
  ('Copas gigantes para ceremonia', 'Decorativos / Mobiliario', 2),
  ('Banquitos de madera usados para rincón de pétalos', 'Decorativos / Mobiliario', 2),
  ('Uniformes variados', 'Decorativos / Mobiliario', null),
  ('Bañera antigua blanca', 'Decorativos / Mobiliario', null),
  ('Bañera retro', 'Decorativos / Mobiliario', null),
  ('Escalera grande de montaje', 'Decorativos / Mobiliario', 1),
  ('Pufs de mimbre', 'Decorativos / Mobiliario', 3),
  ('Letras “LOVE” con bombillas', 'Decorativos / Mobiliario', null),
  ('Cestos con asa', 'Decorativos / Mobiliario', 13),
  ('Cestos para conos de pétalos', 'Decorativos / Mobiliario', 2),
  ('Cestos maxi grandes', 'Decorativos / Mobiliario', 3),
  ('Cestos grandes', 'Decorativos / Mobiliario', 12),
  ('Cestos medianos', 'Decorativos / Mobiliario', 10),
  ('Otros cestos más pequeños', 'Decorativos / Mobiliario', null),
  ('Alfombras persas/kilim', 'Decorativos / Mobiliario', 5),
  ('Alfombra de yute', 'Decorativos / Mobiliario', 1),
  ('Pedestales de madera', 'Decorativos / Mobiliario', 2),
  ('Maceteros grandes de madera', 'Decorativos / Mobiliario', 2),
  ('Peana para colocar flechas', 'Decorativos / Mobiliario', 1),
  ('Caja grande con piñas', 'Decorativos / Mobiliario', 1),
  ('Calderos antiguos', 'Decorativos / Mobiliario', 2),
  ('Cajas variadas', 'Decorativos / Mobiliario', 6),
  ('Caja con cuerdas', 'Decorativos / Mobiliario', 1),
  ('Caja con corchos', 'Decorativos / Mobiliario', 1),
  ('Cajas completas de esponja artificial para flor fresca', 'Decorativos / Mobiliario', 2),
  ('Diversas bandejas de plástico en distintos tamaños para componer centros', 'Decorativos / Mobiliario', null),
  ('Variedad de macetas estilo andaluz', 'Decorativos / Mobiliario', null),
  ('Estructura de madera para seating plan', 'Decorativos / Mobiliario', 1),
  ('Corona preservada', 'Decorativos / Mobiliario', 1),
  ('Cuadro pizarra', 'Decorativos / Mobiliario', 1),
  ('Faroles con vela LED', 'Decorativos / Mobiliario', 8),
  ('Dispensadores de limonada', 'Decorativos / Mobiliario', 6),
  ('Variedad de velas LED', 'Decorativos / Mobiliario', null),
  ('Guirnaldas con micro luces', 'Decorativos / Mobiliario', null),
  ('Guirnaldas con bombillas', 'Decorativos / Mobiliario', null),
  ('Consola gris con puerta y cajón', 'Decorativos / Mobiliario', 1),
  ('Mantones de Manila', 'Decorativos / Mobiliario', null),
  ('Guirnaldas de estilo mexicano', 'Decorativos / Mobiliario', null),
  ('Sombreros mexicanos', 'Decorativos / Mobiliario', null),
  ('Armarios de cocina', 'Taller y almacenaje', 2),
  ('Nevera', 'Taller y almacenaje', 1),
  ('Microondas', 'Taller y almacenaje', 1),
  ('Armarios para herramientas con puertas correderas tipo archivador con diversidad de herramientas y utensilios de montaje', 'Taller y almacenaje', 2),
  ('Armarios grandes blancos donde están guardados jarrones, botellas de cristal, faroles, damajuanas y material de pintura/restauración', 'Taller y almacenaje', 2),
  ('Mesa grande de taller desmontable formada por un tablero plegable y dos caballetes', 'Taller y almacenaje', 1),
  ('Cubos variados de plástico para mantener flores frescas en agua', 'Taller y almacenaje', 22),
  ('Mesa de catering de zinc', 'Taller y almacenaje', 1),
  ('Mesa de hierro de taller', 'Taller y almacenaje', 1),
  ('Cubo grande de basura', 'Taller y almacenaje', 1),
  ('Armario organizador con cajas', 'Taller y almacenaje', 1),
  ('Mochila con ruedas para montajes', 'Taller y almacenaje', 1),
  ('Aspiradora Kärcher', 'Limpieza', 1),
  ('Material de limpieza: escobas, cubos, fregonas y recogedores', 'Limpieza', null)
) as v(articulo, categoria, cantidad)
where not exists (
  select 1 from inventario i where lower(i.articulo) = lower(v.articulo)
);

-- Alpacas / balas de paja: 30 unidades
update inventario set cantidad_total = 30
where lower(articulo) like '%alpaca%';
